# config.yaml

llm:
  provider: "openai" 
  api_key: "${OPENAI_API_KEY}"
  model_name: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  additional_params:
    top_p: 1
    frequency_penalty: 0
    presence_penalty: 0

agent:
  name: "ResearchAgent"
  memory_type: "vector"
  max_memory_items: 1000
  embedding_model: "text-embedding-ada-002"
  document_store: "document_store.json"
  faiss_index: "faiss_index.index"

logging_level: "INFO"
cache_enabled: true
search_provider: "duckduckgo"
max_search_results: 3